In [2]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [4]:
#Code for check the type of variables:
print("Data type of List_",type(list_))
print("Data type of array_list",type(array_list))

Data type of List_ <class 'list'>
Data type of array_list <class 'numpy.ndarray'>


In [4]:
#Answer2
#Code of Data types of objects in both variables:
#print data types of elements in list_:
print("Data types of elements in list_")
for element in list_:
    print(type(element))
    
#print data types of elements in array_list:
print("\nData types of elements in array_list")
for element in array_list:
    print(type(element))

Data types of elements in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [7]:
#Answer3
array_list = np.array(object = list_, dtype = int)
list_ = ['1','2','3','4','5']

In [9]:
print("Data types of elements in list_")
for element in list_:
    print(type(element))
    
#print data types of elements in array_list:
print("\nData types of elements in array_list")
for element in array_list:
    print(type(element))

Data types of elements in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [10]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [17]:
#Answer4
#Code for find the Shape:
print("The shape of num_array is:",num_array.shape)

#code for find the size:
print("\nThe size of num_array is:",num_array.size)

The shape of num_array is: (2, 3)

The size of num_array is: 6


In [20]:
#Answer5:
#A code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
numpy_array = np.zeros((3,3))
print(numpy_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#Answer6:
#Create an identity matrix of shape (5,5) using numpy functions:
numpy_identity_matrix = np.eye(5)
print(numpy_identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
